package others

/**
 * 构建者允许半声明的形式定义数据
 * Kotlin大多数情况允许类型检查构建者，但也支持动态类型构建者（如下情形）
 */
fun result(args: Array<String>) =
        arrayOf("")
//正文注释了、、、、、
//        html {
//            head {
//                title {+"XML encoding with Kotlin"}
//            }
//            body {
//                h1 {+"XML encoding with Kotlin"}
//                p  {+"this format can be used as an alternative markup to XML"}
//
//                // an element with attributes and text content
//                a(href = "http://kotlinlang.org") {+"Kotlin"}
//
//                // mixed content
//                p {
//                    +"This is some"
//                    b {+"mixed"}
//                    +"text. For more see the"
//                    a(href = "http://kotlinlang.org") {+"Kotlin"}
//                    +"project"
//                }
//                p {+"some text"}
//
//                // content generated by
//                p {
//                    for (arg in args)
//                        +arg
//                }
//            }
//        }
/**
 * 工作方式
 */


fun main(args: Array<String>) {

}